# Generated by Django 3.2.19 on 2023-06-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
